name: Deploy

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest


    steps:
      - name: Print Variable
        run: echo "The variable is ${{ secrets.MY_VARIABLE }}"

      - name: Set-up
        uses: actions/setup-node@v4
        with:
          node-version: '18'
