name: Deploy

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Install redis cli
        run: sudo apt-get update -y && sudo apt-get install redis-tools -y

      - name: Test Redis Connection
        run: redis-cli -h localhost -p 6379 ping

      - name: Print Variable
        run: echo "The variable is ${{ secrets.MY_VARIABLE }}"

      - name: Set-up
        uses: actions/setup-node@v4
        with:
          node-version: '18'
