name: Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Print Variable
        run: echo "The variable is ${{ secrets.MY_VARIABLE }}"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set-up
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Build Application
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment-pages.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment-pages
        uses: actions/deploy-pages@v4


  notify:
    runs-on: ubuntu-latest

    needs: deploy

    steps:
      - name: Notify Slack
        uses: 8398/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK}}
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author



        

